title: Dual Booting Ubuntu 22.04
plugins:
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - README.md
remote_theme: jekyll/minima
minima:
  skin: dark
header_pages: ['']

